urlmap = {
'shenghua': {'auth': 'CC',
             'auth2': '冰魂',
             'long': 'https://ckcz123.com/games/shenghua/',
             'short': ['生化研究所——单层', 'shenghua', 't36'],
             'tag': [],
             'towerid': 'shenghua'},  
'24': {'auth': '胖老鼠',
       'auth2': '小艾',
       'long': 'https://ckcz123.com/games/24/',
       'short': ['24层魔塔', '24', 't29'],
       'tag': [{'三原塔': 10000}],
       'towerid': '24'},
'ComplexWorld': {'auth': '花落雨沾湿',
                 'auth2': '小艾',
                 'long': 'https://ckcz123.com/games/ComplexWorld/',
                 'short': ['Complex World', 'ComplexWorld', 't15'],
                 'tag': [{'新': 5}],
                 'towerid': 'ComplexWorld'},
'baobei51': {'auth': '数码宝贝51',
             'auth2': '数码宝贝51',
             'long': 'https://ckcz123.com/games/baobei51/',
             'short': ['魔塔-宝贝51吧 平面休闲塔', 'baobei51', 't35'],
             'tag': [{'首发': 10}, {'新': 5}],
             'towerid': 'baobei51'},
'benghuai3': {'auth': '红衣',
              'auth2': '小艾',
              'long': 'https://ckcz123.com/games/benghuai3/',
              'short': ['崩坏3', 'benghuai3', 't12'],
              'tag': [{'新': 5}],
              'towerid': 'benghuai3'},
'chongsheng': {'auth': '小艾',
               'auth2': '小艾',
               'long': 'https://ckcz123.com/games/chongsheng/',
               'short': ['重生塔', 'chongsheng', 't28'],
               'tag': [{'新': 5}],
               'towerid': 'chongsheng'},
'fengleijidu': {'auth': '见见',
                'auth2': '见见',
                'long': 'https://ckcz123.com/games/fengleijidu/',
                'short': ['风雷缉毒', 'fengleijidu', 't5'],
                'tag': [{'首发': 10}, {'新': 5}],
                'towerid': 'fengleijidu'},
'hansel': {'auth': '阻激夹域',
           'auth2': '小艾',
           'long': 'https://ckcz123.com/games/hansel/',
           'short': ['汉塞尔与格莱特', 'hansel', 't8'],
           'tag': [{'新': 5}],
           'towerid': 'hansel'},
'hanyungu': {'auth': '终末之扉',
             'auth2': '终末之扉',
             'long': 'https://ckcz123.com/games/hanyungu/',
             'short': ['寒云谷', 'hanyungu', 't27'],
             'tag': [{'新': 5}],
             'towerid': 'hanyungu'},
'huanta': {'auth': '淡血雾',
           'auth2': '淡血雾',
           'long': 'https://ckcz123.com/games/huanta/',
           'short': ['幻塔', 'huanta', 't30'],
           'tag': [{'首发': 10}, {'新': 5}],
           'towerid': 'huanta'},
'intermediate': {'auth': 'flynn',
                 'auth2': 'zhaouv',
                 'long': 'https://ckcz123.com/games/intermediate/',
                 'short': ['冥中手', 'intermediate', 't26'],
                 'tag': [{'首发': 10}, {'新': 5}],
                 'towerid': 'intermediate'},
'jia20f': {'auth': '终末之扉',
           'auth2': '淡血雾',
           'long': 'https://ckcz123.com/games/jia20f/',
           'short': ['假·20层魔塔', 'jia20f', 't18'],
           'tag': [{'新': 5}],
           'towerid': 'jia20f'},
'jianchuan1': {'auth': '雨兰清风',
               'auth2': '雨兰清风',
               'long': 'https://ckcz123.com/games/jianchuan1/',
               'short': ['剑主的传说(序章)', 'jianchuan1', 't22'],
               'tag': [{'首发': 10}, {'新': 5}],
               'towerid': 'jianchuan1'},
'jianchuan2': {'auth': '雨兰清风',
               'auth2': '雨兰清风',
               'long': 'https://ckcz123.com/games/jianchuan2/',
               'short': ['剑主的传说（破晓）', 'jianchuan2', 't32'],
               'tag': [{'首发': 10}, {'新': 5}],
               'towerid': 'jianchuan2'},
'jiange': {'auth': '终末之扉',
           'auth2': '终末之扉',
           'long': 'https://ckcz123.com/games/jiange/',
           'short': ['剑阁', 'jiange', 't33'],
           'tag': [{'首发': 10}, {'新': 5}],
           'towerid': 'jiange'},
'jianmo1': {'auth': 'worcher',
            'auth2': '小艾',
            'long': 'https://ckcz123.com/games/jianmo1/',
            'short': ['歼魔计划人类篇', 'jianmo1', 't10'],
            'tag': [{'新': 5}],
            'towerid': 'jianmo1'},
'jinengta': {'auth': '小红帽',
             'auth2': '小红帽',
             'long': 'https://ckcz123.com/games/jinengta/',
             'short': ['普通的技能塔', 'jinengta', 't36'],
             'tag': [{'首发': 10}, {'新': 5}],
             'towerid': 'jinengta'},
'jing6ta': {'auth': '59',
            'auth2': '冰魂',
            'long': 'https://ckcz123.com/games/jing6ta/',
            'short': ['能让641震惊的魔塔', 'jing6ta', 't19'],
            'towerid': 'jing6ta'},
'juesai1f': {'auth': '肥鸡',
             'auth2': '见见',
             'long': 'https://ckcz123.com/games/juesai1f/',
             'short': ['决赛塔1层', 'juesai1f', 't2'],
             'towerid': 'juesai1f'},
'kebianjiadian': {'auth': '小艾',
                  'auth2': '小艾',
                  'long': 'https://ckcz123.com/games/kebianjiadian/',
                  'short': ['可变加点单层塔', 'kebianjiadian', 't23'],
                  'tag': [{'新': 5}],
                  'towerid': 'kebianjiadian'},
'kengta0': {'auth': '专家',
            'auth2': '冰魂',
            'long': 'https://ckcz123.com/games/kengta0/',
            'short': ['坑系魔塔之坑塔', 'kengta0', 't17'],
            'towerid': 'kengta0'},
'kerong': {'auth': '大白貂',
           'auth2': '小艾',
           'long': 'https://ckcz123.com/games/kerong/',
           'short': ['可绒塔', 'kerong', 't25'],
           'tag': [{'首发': 10}, {'新': 5}],
           'towerid': 'kerong'},
'lisaier': {'auth': '鸿儒',
            'auth2': '小艾',
            'long': 'https://ckcz123.com/games/lisaier/',
            'short': ['莉赛尔的仓库', 'lisaier', 't9'],
            'towerid': 'lisaier'},
'lugunshi': {'auth': '魔塔吧会员',
             'auth2': '641',
             'long': 'https://ckcz123.com/games/lugunshi/',
             'short': ['露滚匙', 'lugunshi', 't24'],
             'tag': [{'新': 5}],
             'towerid': 'lugunshi'},
'mengsi': {'auth': '用户名已注销',
           'auth2': '用户名已注销',
           'long': 'https://ckcz123.com/games/mengsi/',
           'short': ['萌死塔', 'mengsi', 't13'],
           'tag': [{'首发': 10}, {'新': 5}],
           'towerid': 'mengsi'},
'mogai24': {'auth': '胖老鼠',
            'auth2': '小艾',
            'long': 'https://ckcz123.com/games/mogai24/',
            'short': ['魔改24层', 'mogai24', 't31'],
            'towerid': 'mogai24'},
'pacman': {'auth': 'zhaouv',
           'auth2': 'zhaouv',
           'authString': '<p class="towerAuthString"><span title="RMB200">悬赏已由<b>花落雨沾湿</b>领取</span></p>',
           'long': 'https://ckcz123.com/games/pacman/',
           'short': ['吃豆人魔塔', 'pacman', 't7'],
           'tag': [{'首发': 10}, {'新': 5}],
           'towerid': 'pacman'},
'random': {'auth': '冰魂',
           'auth2': '冰魂',
           'long': 'https://ckcz123.com/games/random/',
           'short': ['无尽轮回', 'random', 't34'],
           'tag': [{'首发': 10}, {'新': 5}],
           'towerid': 'random'},
'seaend': {'auth': '蓝晶',
           'auth2': '小艾',
           'long': 'https://ckcz123.com/games/seaend/',
           'short': ['海洋的尽头', 'seaend', 't6'],
           'towerid': 'seaend'},
'shilian20f': {'auth': '小艾',
               'auth2': '小艾',
               'long': 'https://ckcz123.com/games/shilian20f/',
               'short': ['20层的试炼', 'shilian20f', 't4'],
               'tag': [{'新': 5}],
               'towerid': 'shilian20f'},
'shilianzhidi': {'auth': '59',
                 'auth2': '小艾',
                 'long': 'https://ckcz123.com/games/shilianzhidi/',
                 'short': ['试炼之地', 'shilianzhidi', 't11'],
                 'towerid': 'shilianzhidi'},
'siwangzhiyu': {'auth': '凌影__戮神歃风',
                'auth2': '小艾',
                'long': 'https://ckcz123.com/games/siwangzhiyu/',
                'short': ['死亡之域', 'siwangzhiyu', 't1'],
                'tag': [{'新': 5}],
                'towerid': 'siwangzhiyu'},
'xiaokenggu': {'auth': '狼族',
               'auth2': '冰魂',
               'long': 'https://ckcz123.com/games/xiaokenggu/',
               'short': ['风之谷2', 'xiaokenggu', 't20'],
               'towerid': 'xiaokenggu'},
'xiaoxiaoluzhu': {'auth': '大白貂',
                  'auth2': '淡血雾',
                  'long': 'https://ckcz123.com/games/xiaoxiaoluzhu/',
                  'short': ['小小露珠之塔', 'xiaoxiaoluzhu', 't21'],
                  'tag': [{'新': 5}],
                  'towerid': 'xiaoxiaoluzhu'},
'yicengxiaota': {'auth': '鸿儒',
                 'auth2': '小艾',
                 'long': 'https://ckcz123.com/games/yicengxiaota/',
                 'short': ['一层小塔', 'yicengxiaota', 't16'],
                 'towerid': 'yicengxiaota'},
'yikongjian': {'auth': 'ss433_2',
               'auth2': '小艾',
               'long': 'https://ckcz123.com/games/yikongjian/',
               'short': ['异空间', 'yikongjian', 't3'],
               'towerid': 'yikongjian'},
'yiluoshenyuan': {'auth': '一条池鱼',
                  'auth2': '小艾',
                  'long': 'https://ckcz123.com/games/yiluoshenyuan/',
                  'short': ['遗落深渊', 'yiluoshenyuan', 't14'],
                  'towerid': 'yiluoshenyuan'},
};